### ISSUE TITLE
Crashes when entering 'cc' cheat

### ISSUE THREAD

**Issue by Rbn3D** [E66666666/GTAVDirectControl#5]
I have been able to compile this (I had to add ``#include <string>` to XInputControl.h, though).

When going in-game, I used `pp` cheat to move the player to the passenger position (that works).
Then, I enter `cc` cheat, and the game crashes instantly.

ScriptHookV shows this error dialog:

![image](https://user-images.githubusercontent.com/4525805/130861131-4d72c019-3d35-4812-9cee-db25e9140238.png)

And adds this line to 'ScriptHookV.log'
`CORE: An exception occurred while executing 'DirectControl.asi' (0x00007FFF948EA7F0), id 36`

Maybe memory addresses needs to be updated?

**Comment by E66666666** [comment]
It's probably that something could not be set. Since you have the source, might be something to look into yourself. It works here, so can't really give pointers. 

Anyway, this is just an experimentation project so I'm not gonna put in effort.
